// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJX8nDDuyxSFHxsi9FMR__xHmV4qgmCng',
    appId: '1:746404515207:web:b9f19b0a7a393143bad722',
    messagingSenderId: '746404515207',
    projectId: 'tms-mobile-app-lite',
    authDomain: 'tms-mobile-app-lite.firebaseapp.com',
    storageBucket: 'tms-mobile-app-lite.firebasestorage.app',
    measurementId: 'G-E3ZDW3674T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9lCUDaeetU1DtFXw9e8Bj9f52AXDj4UY',
    appId: '1:746404515207:android:637a3d06c84a45b8bad722',
    messagingSenderId: '746404515207',
    projectId: 'tms-mobile-app-lite',
    storageBucket: 'tms-mobile-app-lite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo3pEAVhmJ2xY0tPZHNcgf_cw_eMVBfAQ',
    appId: '1:746404515207:ios:de77591420c9e6febad722',
    messagingSenderId: '746404515207',
    projectId: 'tms-mobile-app-lite',
    storageBucket: 'tms-mobile-app-lite.firebasestorage.app',
    iosBundleId: 'com.example.tmsMobileAppLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo3pEAVhmJ2xY0tPZHNcgf_cw_eMVBfAQ',
    appId: '1:746404515207:ios:de77591420c9e6febad722',
    messagingSenderId: '746404515207',
    projectId: 'tms-mobile-app-lite',
    storageBucket: 'tms-mobile-app-lite.firebasestorage.app',
    iosBundleId: 'com.example.tmsMobileAppLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJX8nDDuyxSFHxsi9FMR__xHmV4qgmCng',
    appId: '1:746404515207:web:653abca3f6a48996bad722',
    messagingSenderId: '746404515207',
    projectId: 'tms-mobile-app-lite',
    authDomain: 'tms-mobile-app-lite.firebaseapp.com',
    storageBucket: 'tms-mobile-app-lite.firebasestorage.app',
    measurementId: 'G-9NZN0LZS6R',
  );
}
